usb-utils:
  debian: [usbutils]
  ubuntu: [usbutils]
libopus-dev:
  debian: [libopus-dev]
  ubuntu: [libopus-dev]
libvpx-dev:
  debian: [libvpx-dev]
  ubuntu: [libvpx-dev]
package_publish_test:
  debian: [package_publish_test]
  ubuntu: [package_publish_test]
